services:
  postgres:
    image: postgres:16
    container_name: filos_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pbe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "her%Q7^9G5WSySOiNZv%bPBFxiRQ@alXH0CFr48h$#0@9h@*9F@D9tYcPQnG%9"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pbe"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    entrypoint: ["npm", "run", "dev"]
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: pbe
      DB_USER: postgres
      DB_PASSWORD: "her%Q7^9G5WSySOiNZv%bPBFxiRQ@alXH0CFr48h$#0@9h@*9F@D9tYcPQnG%9"
      DB_SSL: "false"
      DB_LOGGING: "true"
    volumes:
      - ./server:/app/server
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build: ./client
    entrypoint:
      ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "80:3000"
    depends_on:
      - server
    environment:
      - VITE_BACKEND_HOST=http://168.138.154.195:8000
    volumes:
      - ./client:/app/client

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./adminer-dark.css:/var/www/html/adminer-dark.css

volumes:
  postgres_data:
